import test from 'node:test';
import assert from 'node:assert/strict';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { readFile } from 'node:fs/promises';

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const schemaPath = path.join(repoRoot, 'scripts', 'schema-postgres.sql');
const madgradesSchemaPath = path.join(repoRoot, 'scripts', 'schema-madgrades-postgres.sql');

test('postgres schema keeps only the required course-side objects', async () => {
  const schema = await readFile(schemaPath, 'utf8');

  assert.match(schema, /CREATE SCHEMA IF NOT EXISTS madgrades;/);
  assert.match(schema, /CREATE TABLE course_search_fts\s*\(/);

  for (const column of [
    'term_code',
    'course_id',
    'canonical_course_designation',
    'alias_course_designation',
    'alias_course_designation_normalized',
    'alias_course_designation_compact',
    'title',
    'title_normalized',
    'description',
  ]) {
    assert.match(schema, new RegExp(`${column}\\s+TEXT`, 'i'));
  }

  assert.match(schema, /ts\s+tsvector\s+NOT NULL/i);
  assert.match(
    schema,
    /CREATE INDEX idx_course_search_fts_ts ON course_search_fts USING GIN \(ts\)/,
  );
  assert.match(
    schema,
    /json_agg\(course_designation ORDER BY course_designation\)::text AS cross_list_designations_json/,
  );
  assert.match(
    schema,
    /json_build_array\(c\.course_designation\)::text\) AS cross_list_designations_json/,
  );
  assert.doesNotMatch(schema, /INCLUDING ALL/);
  assert.doesNotMatch(schema, /PRAGMA/);
  assert.doesNotMatch(schema, /current_term_section_instructor_grade_overview_v/);
  assert.doesNotMatch(schema, /CREATE TABLE madgrades\.courses/i);
  assert.doesNotMatch(schema, /CREATE TABLE madgrades\.course_search_fts/i);
  assert.doesNotMatch(schema, /CREATE VIEW madgrades\.course_overview_v/i);
  assert.doesNotMatch(schema, /CREATE VIEW madgrades\.section_overview_v/i);

  const sectionOverviewIndex = schema.indexOf('CREATE VIEW section_overview_v');
  const courseOverviewIndex = schema.indexOf('CREATE VIEW course_overview_v');
  assert.notEqual(sectionOverviewIndex, -1);
  assert.notEqual(courseOverviewIndex, -1);
  assert.ok(sectionOverviewIndex < courseOverviewIndex);

  const dropCourseOverviewIndex = schema.indexOf('DROP VIEW IF EXISTS course_overview_v;');
  const dropSectionOverviewIndex = schema.indexOf('DROP VIEW IF EXISTS section_overview_v;');
  assert.notEqual(dropCourseOverviewIndex, -1);
  assert.notEqual(dropSectionOverviewIndex, -1);
  assert.ok(dropCourseOverviewIndex < dropSectionOverviewIndex);
});

test('postgres schema uses import-friendly identity columns', async () => {
  const schema = await readFile(schemaPath, 'utf8');

  assert.match(
    schema,
    /refresh_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY/,
  );
  assert.doesNotMatch(
    schema,
    /refresh_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY/,
  );
});

test('postgres schema uses bigint for epoch-millisecond course timestamps', async () => {
  const schema = await readFile(schemaPath, 'utf8');

  assert.match(schema, /package_last_updated BIGINT,/);
  assert.match(schema, /source_package_last_updated BIGINT,/);
  assert.match(schema, /start_date BIGINT,/);
  assert.match(schema, /end_date BIGINT,/);
  assert.match(schema, /exam_date BIGINT,/);

  assert.match(
    schema,
    /CREATE TABLE canonical_meetings \([\s\S]*start_date BIGINT,[\s\S]*end_date BIGINT,[\s\S]*exam_date BIGINT,/,
  );
});

test('madgrades postgres schema includes the standalone madgrades objects only', async () => {
  const schema = await readFile(madgradesSchemaPath, 'utf8');

  assert.match(schema, /CREATE SCHEMA IF NOT EXISTS madgrades;/);
  assert.match(schema, /SET search_path = madgrades;/);

  for (const tableName of [
    'madgrades_refresh_runs',
    'madgrades_courses',
    'madgrades_course_subject_aliases',
    'madgrades_course_names',
    'madgrades_instructors',
    'madgrades_course_grades',
    'madgrades_course_grade_distributions',
    'madgrades_instructor_grades',
    'madgrades_instructor_grade_distributions',
    'madgrades_course_offerings',
    'madgrades_course_matches',
    'madgrades_instructor_matches',
  ]) {
    assert.match(schema, new RegExp(`CREATE TABLE ${tableName}\\s*\\(`));
    assert.match(schema, new RegExp(`DROP TABLE IF EXISTS ${tableName};`));
  }

  for (const indexName of [
    'idx_madgrades_courses_designation',
    'idx_madgrades_course_subject_aliases_course',
    'idx_madgrades_course_names_course',
    'idx_madgrades_course_grades_course_term',
    'idx_madgrades_course_offerings_course_instructor_term',
    'idx_madgrades_instructor_grades_instructor_term',
    'idx_madgrades_course_matches_course',
    'idx_madgrades_instructor_matches_instructor',
  ]) {
    assert.match(schema, new RegExp(`CREATE INDEX ${indexName}`));
  }

  assert.match(
    schema,
    /UNIQUE \(madgrades_course_id, madgrades_instructor_id, term_code, section_type\)/,
  );
  assert.doesNotMatch(schema, /PRAGMA/);
  assert.doesNotMatch(schema, /CREATE TABLE courses\s*\(/);
  assert.doesNotMatch(schema, /CREATE TABLE packages\s*\(/);
  assert.doesNotMatch(schema, /CREATE TABLE course_search_fts\s*\(/);
  assert.doesNotMatch(schema, /CREATE VIEW course_overview_v\s+AS/);
  assert.doesNotMatch(schema, /CREATE VIEW schedule_candidates_v\s+AS/);
});

test('madgrades postgres schema uses import-friendly identity primary keys', async () => {
  const schema = await readFile(madgradesSchemaPath, 'utf8');

  const identityPrimaryKeys = [
    'madgrades_refresh_run_id',
    'madgrades_course_id',
    'madgrades_instructor_id',
    'madgrades_course_grade_id',
    'madgrades_course_grade_distribution_id',
    'madgrades_instructor_grade_id',
    'madgrades_instructor_grade_distribution_id',
    'madgrades_course_offering_id',
  ];

  for (const column of identityPrimaryKeys) {
    assert.match(
      schema,
      new RegExp(`${column} INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY`),
    );
    assert.doesNotMatch(
      schema,
      new RegExp(`${column} INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY`),
    );
  }

  assert.doesNotMatch(schema, /GENERATED ALWAYS AS IDENTITY/);
});
